---
apiVersion: v1
kind: service       # clusterIP by defualt
metadata:
  name: web-tier-service
spec:
  selector: 
    app: web-tier      
ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
